### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by wdeback** [margrietpalm/VisGrid3D#1]
First off: Great job, Margriet! 

However, I noticed some issues:

1. Although all VTK files seems to be read, all generated PNG files show the first (t=0) step.

2.  When generating still images [-s], it does not terminate when finished (starts over with first image).

```
...
./027.png
./028.png
./029.png
./000.png
./001.png
./002.png
./003.png
...
```

FYI: I did not explicitly set the steps with the [--steps] option.

**Comment by margrietpalm** [comment]
> Although all VTK files seems to be read, all generated PNG files show the first (t=0) step.

I have no idea what is happening here. Could you share the command you used and a morpheus xml that generates the vtk files (or just the vtk files)? 

> When generating still images [-s], it does not terminate when finished (starts over with first image).

Argh, that was not supposed to happen, and it is fixed now.

**Comment by wdeback** [comment]
Command (executed from results directory):
`visgrid3D -i . -t 1 2 -c red green -a 0.75 0.75 -s -m`

Model, based on Examples/CPM/CellSorting_3D.xml: [TestVisGrid3D.xml.zip](https://github.com/margrietpalm/VisGrid3D/files/681364/TestVisGrid3D.xml.zip)
(had to zip it as github doesn't like xml files)

Here's the result for all of the png files:

![005](https://cloud.githubusercontent.com/assets/22352183/21596085/68b9981e-d136-11e6-8777-1e676d24c748.png)


To confirm that there is data in the vtk files, here's the rendering of the 5th step with paraview:

![paraview005](https://cloud.githubusercontent.com/assets/22352183/21596077/53dd7186-d136-11e6-9404-1c143aac95f0.png)

**Comment by margrietpalm** [comment]
This issue should be fixed now as well. I incorrectly set the static cell types to all cell types when `--static` was omitted.

**Comment by wdeback** [comment]
Yes, fixed, thanks.  Closing issue.
