### ISSUE TITLE
Missing src/movie.h

### ISSUE THREAD

**Issue by wdeback** [margrietpalm/VisGrid3D#2]
When configuring, cmake complains that:

```
CMake Error at CMakeLists.txt:23 (add_executable):
  Cannot find source file:

    src/movie.h
```

Workaround: comment out this line in CMakeLists.txt (but generating movies is presumably not possible).

**Comment by margrietpalm** [comment]
Thanks for reporting this. Fixed this in commit 4730ecf5ad5c0a0810ce86d17686e9de4ebb6d43.

FYI, I started on building movie support in a separate branch, but it is not yet working.
