### ISSUE TITLE
Compilation on OSX

### ISSUE THREAD

**Issue by wdeback** [margrietpalm/VisGrid3D#3]
When compiling on Mac OSX with Macports under GCC, I got this error:

```
Undefined symbols for architecture x86_64:
"vtkObjectBase::PrintHeader(...
```

This is due to a libc++ / libstdc++ incompatibility in the VTK port (http://code.opencv.org/issues/3582).

Solution: Compile with `clang++` instead of `gcc`.

**Comment by margrietpalm** [comment]
Thanks for reporting. Whenever I get to optimizing the cmake setup for multiple platforms I'll include this. For know I'll just mention it in the readme.
